import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { headers } from "next/headers";
import Footer from "@/components/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
let currentURL = "";
export default async function RootLayout({ children }) {
    const headersList = await headers();
    const pathname = headersList.get('x-pathname') || '';

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col`}
            >
                {pathname?.includes("/admin") ? null : <Header />}

                <main className="flex-grow">{children}</main>

                {pathname?.includes("/admin") ? null : <Footer />}
                {/* <p>{currentURL}</p> */}
            </body>
        </html>
    );
}
